FROM ubuntu:22.04
RUN apt-get update && \
    apt-get install -y \
    libnetfilter-queue-dev \
    iptables \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y g++
RUN apt-get update && \
    apt-get install -y cmake && \
    rm -rf /var/lib/apt/lists/*
RUN apt-get update && \
    apt-get install -y libpcap-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /VPN/code/VPNServer/ubuntu22

CMD [ "/bin/sh", "-c", "cmake .. -DFROM_DOCKER=TRUE && make" ]